name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Sample Commands
          run: |
             echo "A initial message"
             echo "This is a Test"
            shell: bash
              run: |
                 pwd
                 ls -al


