name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Sample Commands
        - uses: actions/checkout@v1
        - run: |
             echo "A initial message"
             echo "This is a Test"
