name: Build and push Docker image
services:
  nginx:
    depends_on:
      - reverseproxy
    image: nginx:alpine
on:
  push:

jobs:
  build-publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: sdatla1/sampleProject@v1
      - uses: actions/checkout@v1
      - name: Build and Push to DockerHub
        run: |
          docker ps
          docker ps --filter status=running
      - name: Run the script
        shell: bash
        run: ./sampleScript.sh