name: 'Welcome Message'
description: 'Greet with Welcome Message'
on: [push]
services:
  nginx:
    depends_on:
      - reverseproxy
    image: nginx:alpine
jobs:
  Welcome_job:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
        - name: Check the docker process
         id : Verify docker process
         uses: sdatla1/sampleProject@v1
         run: |
            docker ps -eaf
            docker ps --filter status=running