on: [push]
runs:
  using: 'docker'
  image: 'Dockerfile'
jobs:
  Docker_job:
    steps:
      - name: Check the docker process
        id: Verify the docker process
        run: |
            docker ps -eaf
            docker ps --filter status=running