on:
  push:
jobs:
  build-publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: sdatla1/sampleProject@v1
      - uses: actions/checkout@v1
      - runs:
            using: 'docker'
            image: 'Dockerfile'
      - name: Build and Push to DockerHub
        run: |
          docker ps
          docker ps --filter status=running
      - name: Run the local script on the docker container
        shell: bash
        run: ./sampleScript.sh