on: [push]
jobs:
  Welcome_job:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - name: Check the docker process
        id: Verify the docker process
        run: |
            docker ps -eaf
            docker ps --filter status=running