services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
on:
  push:

jobs:
  build-publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: sdatla1/sampleProject@v1
      - uses: actions/checkout@v1
      - name: Build and Push to DockerHub
        run: |
          docker ps
          docker ps --filter status=running
      - name: Run the script
        shell: bash
        run: ./sampleScript.sh