on: [push]

jobs:
  Welcome_job:
    runs-on: ubuntu-latest
    name: Welcome Message
    steps:
      - name: Welcome action step
        id: Welcome
        uses: sdatla1/sampleProject@v1
        with:
          who-to-greet: 'Subha Datla'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"